name: Terraform Destroy Dev Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS region'
        required: false
        default: 'us-east-1'

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.13.2"
  AWS_ACCOUNT_ID: "333888905249"

jobs:
  destroy-dev:
    name: Destroy dev environment infrastructure
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          # role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/OICD-joo-access
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}


      
      - name: Configure Terraform Plugin Cache
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: environments/dev
