name: Terraform Dev-Environment 

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - "environments/dev/**"
      - "modules/**"

      
permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-dev
  cancel-in-progress: false

env:
  TF_VERSION: "1.13.2"
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "333888905249"

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: dev

    outputs:
      changes: ${{ steps.plan.outputs.changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          # role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/OICD-joo-access
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Cache Terraform Providers
        uses: actions/cache@v5.1.0
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Configure Terraform Plugin Cache
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.0

      - name: Initialize TFLint
        run: tflint --init
        working-directory: environments/dev

      - name: Run TFLint
        run: tflint
        working-directory: environments/dev

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: environments/dev
          framework: terraform
          quiet: true
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        shell: bash
        working-directory: environments/dev
        run: |
          set +e

          terraform plan -out=tfplan -detailed-exitcode

          EXIT_CODE=$?

          if [ "$EXIT_CODE" -eq 1 ]; then
            exit 1
          elif [ "$EXIT_CODE" -eq 2 ]; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate Plan Output
        if: steps.plan.outputs.changes == 'true'
        run: terraform show tfplan > tfplan.txt
        working-directory: environments/dev

      - name: Upload Binary Plan
        if: steps.plan.outputs.changes == 'true'
        uses: actions/upload-artifact@v7.0.1
        with:
          name: terraform-plan
          path: environments/dev/tfplan

      - name: Upload Plan Output
        if: steps.plan.outputs.changes == 'true'
        uses: actions/upload-artifact@v7.0.1
        with:
          name: terraform-plan-output
          path: environments/dev/tfplan.txt

  apply:
    name: Terraform Apply
    needs: plan
    if: needs.plan.outputs.changes == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: dev  

    steps:
      - name: Checkout
        uses: actions/checkout@v5.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          # role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/OICD-joo-access
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Cache Terraform Providers
        uses: actions/cache@v5.1.0
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Configure Terraform Plugin Cache
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Download Binary Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: environments/dev

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: environments/dev
